version: '3.7'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - "api.network"

  mysqldb:
    image: mariadb:10.6.4-focal
    volumes:
      - videoDB:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=videodb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
     - "3307:3306"
    networks:
      - "api.network"

  
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - "api.network"

  database:
    image: tristan007/3496-database:latest
    ports:
      - "8000:8000"
    environment:
      - PASSWORD=password
      - DB=videodb
      - USER=root
      - PORT=3307
      - HOST=mysqldb
    depends_on:
      - mysqldb
    networks:
      - "api.network"

  filesystem:
    build: tristan007/3496-file-system:latest
    ports:
      - "8070:8070"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-west-2
    networks:
      - "api.network"

  upload_web_app:
    build: tristan007/3496-upload-video:latest
    ports:
      - "4200:80" 
    depends_on:
      - auth
      - database
    environment:
      - DATABASE=database
    networks:
      - "api.network"

  streaming_web_app:
    build: tristan007/3496-video-streaming:latest
    ports:
      - "4201:80" 
    depends_on:
      - auth
      - database
    environment:
      - DATABASE=database
    networks:
      - "api.network"

volumes:
  redis-data:
  videoDB:

networks:
  api.network:


