---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: us-west-2
  MYSQL_DATABASE: videodb
  MYSQL_USER: user
  DB: videodb
  USER: root
  PORT: "3307"
  HOST: mysqldb

---
apiVersion: v1
kind: Secret
metadata:
  name: password-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  PASSWORD: cGFzc3dvcmQ=